update:
  cooldown_days: 7
  freeze: true
  exclude_tags: ["*-{alpha,beta,rc}*", "*[0-9][ab][0-9]*", "*[0-9]rc[0-9]*"]
exclude: "^(src/memray/reporters/templates/assets|src/vendor|benchmarks|docs/_static/flamegraphs)/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: "^asv\\.conf\\.json$"
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: "^([.]bumpversion[.]cfg|.*/__snapshots__/)"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316 # frozen: v1.10.0
    hooks:
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "44b5042edab9382aba712eed4f9c7bab7a3d6a3e" # frozen: v0.17.0
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 9f905615631c545f5aea2516508109350d1d2f7d # frozen: 9.0.2
    hooks:
      - id: isort
        exclude_types: [python]

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: c883505f64b59c3c5c9375191e4ad9f98e727ccd # frozen: v1.0.2
    hooks:
      - id: sphinx-lint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier
        args: [--no-editorconfig]
        exclude: "^asv\\.conf\\.json$"
        exclude_types: [html]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: a9a8a861f30ed207ead7d5a3b7e8032283ba5da7 # frozen: v23.1.2
    hooks:
      - id: clang-format
        args: [--Werror, -i]
        exclude: "^tests/integration/"
        types_or: [c++, c, cuda]

  - repo: https://github.com/rstcheck/rstcheck
    rev: d8774e96810795967ed9603f445b4e751e7b313f # frozen: v6.3.0
    hooks:
      - id: rstcheck
        files: ^news/
        types: [rst]
        additional_dependencies: ["sphinx"]
