default_install_hook_types: [pre-commit, pre-push]
exclude: "^(src/memray/reporters/templates/assets|src/vendor|benchmarks|docs/_static/flamegraphs)/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-json
        exclude: "^asv\\.conf\\.json$"
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        exclude: "^[.]bumpversion[.]cfg"
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-directive-colons
        stages: [pre-commit]
      - id: rst-inline-touching-normal
        stages: [pre-commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.262"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [pre-commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude_types: [python]
        stages: [pre-commit]

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.7
    hooks:
      - id: sphinx-lint
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--no-editorconfig]
        exclude: "^asv\\.conf\\.json$"
        exclude_types: [html]
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.2
    hooks:
      - id: clang-format
        args: [--Werror, -i]
        exclude: "^tests/integration/"
        stages: [pre-commit]
        types_or: [c++, c, cuda]

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.2
    hooks:
      - id: rstcheck
        files: ^news/
        stages: [pre-commit]
        types: [rst]
        additional_dependencies: ["sphinx"]

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        stages: [pre-push]
