name: 🚀 Feature Request
description: Suggest an idea for this project
labels: [enhancement]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing proposal for this?
      description: Please search to see if a proposal already exists for this feature.
      options:
        - label: I have searched the existing proposals
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: |
        I have an issue when [...]
    validations:
      required: True
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Add any considered drawbacks.
      placeholder: |
        I would love if Memray could [...]
    validations:
      required: True
  - type: textarea
    attributes:
      label: Alternatives you considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: False
